articles/urls.py
from django.urls import path
from . import views




app_name = 'articles'
# /articles/ _____

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),


    # path('new/',views.new, name='new'), 
    path('create/', views.create, name='create'),
    # /article/4/delete/
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    
    path('<int:article_pk>/update/', views.update, name='update'),
    # /article/3/comments/
    path('<int:article_pk>/comments',views.comments_create, name='comments_create')
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
]

jobs/urls.py
from django.urls import path
from . import views




app_name = 'jobs'
# /jobs/ _____

urlpatterns = [
    path('', views.index, name='index'),
    path('past_jobs/', views.create, name='create'),

]

articles/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    #시험 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    # on_delete = models.CASCADE 는  article이 삭제되면 comment도 함께 삭제
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk']
    
    def __str__(self):
        return self.name

jobs/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()
    def __str__(self):
        return self.name

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
# Create your views here.
#articles의 메인페이지, article list를 보여줌


def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/index.html', context)



#입력페이지 제공
#GET /articles/create/ -> 페이지만 받아가겠다.
# def new(request):
#     return render(request, 'articles/new.html')


#데이터를 전달받아 article 생성하는 페이지
#POST /articles/create/
def create(request):
    # 요청이 POST라면 사용자 데이터 받아서 article 생성
    # /articles/new/의 new.html의 form에서 전달받은 데이터들
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')

        article = Article()
        article.title = title
        article.content = content
        article.save()

        return redirect('articles:detail', article.pk)  

    else:
        # 만약 GET 요청으로 들어오면 html 페이지 렌더링
        return render(request, 'articles/create.html')


def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST': 
        article.delete()
        return redirect('articles:index')

    else:
        return redirect('articles:detail', article_pk)

def update(request, article_pk):
    # POST : 실제 UPDATE 로직 수행
    # GET : UPDATE를 하기위한 FORM을 제공하는 페이지
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        article.title = title
        article.content = content
        article.save()
        
        return redirect('articles:detail', article.pk)  

    else:
        context ={
            'article' : article,
        }
        return render(request, 'articles/update.html', context)

# variable Routing으로 사용자가 원하는 페이지를 pk로 받아 
# Detail 페이지를 보여준다.
def detail(request, article_pk):
    # SELECT * FROM articles WHERE pk=3 이런느낌의...
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comment_set.all()
    context = {
        'article' : article,
        'comments' : comments,
    }
    return render(request, 'articles/detail.html', context)

def comments_create(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        content = request.POST.get('content')
        comment = Comment()
        comment.content = content
        comment.article = article
        comment.save()
    # article_pk에 해당하는 article에 새로운 comment 생성
    # 생성한 다음 article detail page 로 redirect
        return redirect('articles:detail', article_pk)

jobs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Job
from faker import Faker
# Create your views here.
import requests
def index(request):

    return render(request, 'jobs/index.html')


def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        jobs = Job.objects.all()
        for job in jobs:
            if job.name == name:
                data = requests.get(f'http://api.giphy.com/v1/gifs/search?api_key=zAckuQru8VqfxKXUnt3EqtHCYD8veI4K&q={job.past_job}').json() # data 는 dict 타입의 객체!
                picture = data['data'][0]['images']['fixed_width']['url']
                context = {
                    'job' : job,
                    'picture' : picture,
                    }
                return render(request, 'jobs/past_job.html', context)
        
        fake = Faker()
        job = Job()
        job.name = name
        job.past_job = fake.job()
        job.save()  
        data = requests.get(f'http://api.giphy.com/v1/gifs/search?api_key=zAckuQru8VqfxKXUnt3EqtHCYD8veI4K&q={job.past_job}').json() # data 는 dict 타입의 객체!
        picture = data['data'][0]['images']['fixed_width']['url']
        context = {
            'job' : job,
            'picture' : picture,
        }
        return render(request, 'jobs/past_job.html', context)
    else:
        return redirect('articles:index')

articles/templates/articles/create.html
{% extends 'base.html' %}
{% block title %} new {% endblock title %}

{% block body %}
  <h1>New Articles</h1>
  <form action="{% url 'articles:create'  %}" method="POST">
    {% csrf_token %}
    <input type="text" name='title'><br>
    <textarea name="content" cols="30" rows="10"></textarea><br>
    <button type="submit">작성하기</button>
  </form>
  <a href="{% url 'articles:create' %}">[뒤로가기]</a>
{% endblock body %}

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block title %}detail{% endblock title %}

{% block body %}
  <h1>{{ article.title }}</h1>
  <p>작성일자: {{ article.created_at }}</p>
  <hr>
  <p> {{ article.content }} </p>
  <hr>
  <h2>comments</h2>
  {% comment %} 코멘트 저장 폼 {% endcomment %}
  <form action="{% url 'articles:comments_create' article.pk %}", method="POST">
    {% csrf_token %}
    <input type="text" name="content">
    <button type="submit">댓글 작성</button>
  </form>
  {% for comment in comments %}
  <div>
    <li>{{ comment.content }}</li>
    {% empty %}
      <p>아직 댓글이 없습니다...</p>
  </div>
  <br>
  {% endfor %}
  <hr>
  <a href="{% url 'articles:index' %}">[뒤로가기]</a>
  <a href="{% url 'articles:update' article.pk %}">[수정하기]</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit">삭제하기</button>
  </form>





  {% comment %} <a href="{% url 'articles:delete' article.pk %}">[삭제하기]</a> {% endcomment %}
{% endblock body %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %} Index{% endblock title %}
{% block body %}
  <h1>Articles</h1>
  <a href="{% url 'articles:create' %}">[작성하기]</a>
  <hr>
  {% for article in articles %}
  <div>
    <h3><a href="{% url 'articles:detail' article.pk %}">{{ article.pk }}. {{ article.title }}</a></h3>
    <p> {{ article.content }} </p>
    
  </div>
  <br>
  {% endfor %}
{% endblock body %}

articles/templates/articles/new.html
{% extends 'base.html' %}
{% block title %} new {% endblock title %}

{% block body %}
  <h1>New Articles</h1>
  <form action="{% url 'articles:create'  %}">
    <input type="text" name='title'><br>
    <textarea name="content" cols="30" rows="10"></textarea><br>
    <button type="submit">작성하기</button>
  </form>
{% endblock body %}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% block title %} update {% endblock title %}

{% block body %}
  <h1>Update Articles</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="text" name='title' value ="{{ article.title }}"><br>
    <textarea name="content" cols="30" rows="10">{{ article.content }}</textarea><br>
    <button type="submit">수정하기</button>
  </form>
  <a href="{% url 'articles:index' %}">[뒤로가기]</a>
{% endblock body %}

crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %} {% endblock title %}</title>
</head>
<body>
  {% block body %}
  
  {% endblock body %}
</body>
</html>

jobs/templates/jobs/index.html
{% extends 'base.html' %}
{% block title %} JOBS index{% endblock title %}
{% block body %}
  <h1>당신의 전생직업은?</h1>
  <h2>이름을 입력하세요.</h2>
  <form action="{% url 'jobs:create' %}" method="post">
    {% csrf_token %}
    <input type="text" name='name'><br>
  <button type="submit">결과보기</button>
  </form>
{% endblock body %}

jobs/templates/jobs/past_job.html
{% extends 'base.html' %}
{% block title %}past_job{% endblock title %}
{% block body %}
  <h1>{{ job.name }}은 전생에 {{ job.past_job }}이었습니다.</h1>
  <img src="{{ picture }}" alt="">
  <a href="{% url 'jobs:index' %}">[뒤로가기]</a>
{% endblock body %}